<a href="https://colab.research.google.com/github/JoseDavidFull/Codigo/blob/main/Examen_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
'''
Reshape y Arange:
Enunciado: Crea una matriz 1D con números enteros en un rango de 1 a 10.
Luego, utiliza reshape para convertirla en una matriz 2D de 2 filas y 5 columnas.
'''
#Ejercicio1
import numpy as np

matriz1D = np.arange(1,11).reshape(2,5)
print(matriz1D)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
'''
Size y Random.rand:
Enunciado: Genera una matriz aleatoria de tamaño 3x4 con números decimales entre
0 y 1. Calcula la suma de todos los elementos de la matriz.
'''
#Ejercicio Num2

import numpy as np
matriz = np.random.randn(3,4)
print(matriz)

matriz.size

[[ 0.84598156  0.20085819 -0.40218756  1.84168939]
 [-0.43659502  1.20715961 -0.35545087 -1.16025134]
 [ 0.59420609 -0.70882818  1.45066709  0.56720179]]


12

In [47]:
'''
Axis y Mean:
Enunciado: Crea una matriz 2D con números enteros y calcula
la media de cada columna (axis=0) y cada fila (axis=1).
Comprueba si el resultado es una matriz 1D.
'''
#Ejercicio Num3
import numpy as np # importamos numpy

matriz2D = np.random.randint(0,25,(5,5))
print(matriz2D)

matriz2D.mean(axis=0)
print("\n")
matriz2D.mean(axis=1)

[[17  9 12 23 15]
 [17 11  4 21  1]
 [ 1  2  3 15 22]
 [16  7  1 18 13]
 [ 8 21 20 20 19]]




array([15.2, 10.8,  8.6, 11. , 17.6])

In [50]:
'''
Random.randint y PTP:
Enunciado: Genera una matriz 3x3 de números enteros aleatorios en el rango de
1 a 20. Calcula la diferencia entre el valor máximo y mínimo de la matriz utilizando ptp.
'''
#Ejercicio Num4
import numpy as np

matriz = np.random.randint(1,21,(3,3))
print(matriz)
matriz.ptp()

[[17  5  5]
 [17 18  6]
 [ 7  9  5]]


13

In [57]:
'''
Shape y Ones:
Enunciado: Crea una matriz 2D de tamaño 4x6 con números enteros.
Luego, utiliza la función ones para crear una matriz del mismo
tamaño, pero con todos los elementos establecidos en 1. Realiza
la suma elemento por elemento de las dos matrices.
'''
#Ejercicio Num5

import numpy as np

matriz2D = np.random.randint(1,25,(4,6))
on = np.ones_like(matriz2D)

suma = 0

for n in on:
  suma+=n
print(suma)


[4 4 4 4 4 4]
