<a href="https://colab.research.google.com/github/JoseDavidFull/Codigo/blob/main/Examen_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
'''Crea un tensor de tamaño (4, 5, 3) con valores aleatorios flotantes utilizando torch.randn.
Accede al elemento en la posición (2, 3, 1) del tensor.
Muestra las dimensiones del tensor y su tipo de dato.
Operaciones con GPU y CPU:'''
#primer ejercio de torch
import torch

device = torch.device('cuda' if torch.cuda.is_available else 'cpu')

tensor = torch.randn(4,5,3)
tensor[2,3,1]

print("Con gpu")
tensor = tensor.to(device)
print(tensor)

print("Con cpu")
cpu = tensor.cpu()
print(cpu)

Con gpu
tensor([[[-0.9222,  1.4455, -0.7941],
         [-2.2287,  0.0432,  1.6626],
         [ 0.4521,  0.0978,  0.5842],
         [ 1.3370,  0.5062, -0.9606],
         [ 0.2608,  3.3711, -0.7416]],

        [[ 1.0628,  1.9544, -1.1928],
         [-0.8577, -0.9217,  1.3312],
         [ 2.8365,  1.4417,  0.5688],
         [ 0.1202, -0.2333,  0.7973],
         [-0.4009, -0.3423, -1.6063]],

        [[-0.5882,  0.0709,  1.6954],
         [ 0.5670,  3.0001, -0.7609],
         [-0.3627,  0.9576,  1.0292],
         [ 0.7931,  1.1938, -1.5944],
         [-0.5601,  0.5062, -1.3115]],

        [[ 0.6649, -0.9265, -2.6494],
         [ 0.0240,  0.0763,  0.8549],
         [-0.6865,  0.4509, -0.7581],
         [ 0.5229, -0.2473,  2.3231],
         [ 1.1133, -0.0857, -0.3289]]], device='cuda:0')
Con cpu
tensor([[[-0.9222,  1.4455, -0.7941],
         [-2.2287,  0.0432,  1.6626],
         [ 0.4521,  0.0978,  0.5842],
         [ 1.3370,  0.5062, -0.9606],
         [ 0.2608,  3.3711, -0.7416]],

       

In [10]:
'''
Operaciones con GPU y CPU:
Crea un tensor de unos con dimensiones (3, 3) utilizando torch.ones.
Verifica si la GPU está disponible y, si es así, mueve el tensor a la GPU utilizando to(device).
Realiza alguna operación (por ejemplo, multiplicación por escalar) en el tensor y muestra el resultado.
Lleva el tensor de vuelta a la CPU utilizando cpu().'''
#ejercicios Num2
import torch #importamos la librera de torch

device = torch.device('cuda' if torch.cuda.is_available else 'cpu')

tensor = torch.ones(3,3) # creacion de tensor de unos de 3x3
torch.cuda.is_available() # verificar si la gpu esta disponible

tensor = tensor.to(device) # mover de cpu a gpu
mul = 1
for n in tensor:
  mul*=n

print("La Multiplicacion es: ",mul)

La Multiplicacion es:  tensor([1., 1., 1.], device='cuda:0')


In [15]:
'''
Generación de Números Enteros y Suma de Matrices:
Genera un tensor de números enteros aleatorios en el rango de 0 a 5
(inclusive) con dimensiones (2, 3) utilizando torch.randint.
Crea dos matrices aleatorias con dimensiones (3, 4) y (4, 2) utilizando torch.randn.
Realiza una multiplicación de matrices entre las dos matrices creadas utilizando mm.
'''
#ejercicio Num3
import torch # importamo torch

tensor = torch.randint(0,6,(2,3))
print(tensor)

tensor1 = torch.randn(3,4)
tensor2 = torch.randn(4,2)

mul = torch.mm(tensor1,tensor2)
print(mul)

tensor([[4, 2, 5],
        [4, 4, 4]])
tensor([[-1.6759,  5.0164],
        [-0.7444, -1.0002],
        [-0.1855, -1.7979]])


In [21]:
'''
Manipulación Eficiente de Dispositivos:
Crea un tensor de tamaño (5, 6, 7) con valores aleatorios.
Verifica si la GPU está disponible y, si es así, mueve el tensor a la GPU.
Realiza alguna operación en el tensor y mide el tiempo de ejecución.
Lleva el tensor de vuelta a la CPU .
'''
#Ejercicios Num4
import torch # importar torch

device = torch.device('cuda' if torch.cuda.is_available else 'cpu') #uso de la gpu y la cpu

tensor = torch.randn(5,6,7) # creacion de el tensor tamaño 5,6,7

torch.cuda.is_available() # true significa que si esta disponible

Gpu = tensor.to(device) # llevando a la gpu

Cpu = tensor.cpu()

print("Llevado a la GPU")
print(Gpu)

print("LLevado a la cpu")
print(Cpu)

Llevado a la GPU
tensor([[[-6.6629e-02,  1.1965e+00,  9.8827e-01, -2.3377e-01, -2.1139e+00,
           1.0737e+00,  1.2208e+00],
         [-3.6347e-01,  5.8236e-01,  3.6409e-01, -1.2571e+00,  8.6748e-01,
          -1.1737e+00,  5.5726e-01],
         [ 2.5233e+00,  1.8456e-01,  1.7218e-01,  1.5732e+00,  4.3519e-01,
          -9.1663e-01,  6.4943e-01],
         [ 4.7620e-01, -5.2412e-01,  1.9362e+00,  4.9971e-01,  1.1573e-01,
           5.2431e-01, -1.0123e-01],
         [ 6.0340e-01,  5.2751e-02,  9.7159e-01,  1.9722e-01,  5.5749e-02,
          -2.7518e+00, -8.4692e-01],
         [-6.0014e-01,  1.6215e+00,  1.7061e-01,  1.4960e-01, -2.6733e-01,
           1.5624e-01,  1.1206e+00]],

        [[ 7.1596e-01, -2.7843e-01, -9.6694e-01, -2.3183e-01, -1.3681e+00,
           5.1788e-01, -4.4680e-01],
         [ 7.6510e-01,  7.9000e-01, -4.3067e-01,  9.6590e-01,  1.7670e-02,
           4.5533e-01, -1.0592e+00],
         [-4.2866e-01, -2.7030e-01, -7.7307e-01,  6.5814e-01, -7.8626e-02,
          

In [24]:
'''
Uso de ones_like y randn en GPU:
Crea un tensor en la GPU con las mismas dimensiones que otro tensor aleatorio creado con torch.randn.
Realiza alguna operación entre los dos tensores y muestra el resultado.
'''

import torch # importamos Pytorch

tensor = torch.randn(3,3, device=device) # creacion de tensor en la gpu
print(tensor)

suma = 0
for n in tensor:
  suma+=n

print("Suma de tensor")
print(suma)

tensor([[-0.9821,  0.1474,  0.3054],
        [ 0.0715,  1.4168,  1.6322],
        [-0.8570, -0.4359, -0.5777]], device='cuda:0')
Suma de tensor
tensor([-1.7676,  1.1283,  1.3600], device='cuda:0')
